module_config: 
    module_type: "latent-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: True
    num_classes: 1000

datamodule_config: 
    dataset: "imagenet"
    batch_size: 128
    num_workers: 8 

train_config: 
    max_steps: 1000000
    val_check_interval: 5000
    check_val_every_n_epoch: null
    accelerator: "auto" 
    precision: "bf16-mixed"
    enable_progress_bar: False

model_checkpoint_config: 
    dirpath: "checkpoints/latent-diffusion/imagenet/fp/"
    filename: "latent-diffusion-imagenet-fp_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "latent-diffusion-imagenet"
  name: "latent-diffusion-fp"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: null