module_config: 
    checkpoint: "/home/oeg1n18/TS-TRQ/checkpoints/latent-diffusion/imagenet/fp/latent-diffusion-imagenet-fp_epoch=11_val_loss=0.186.ckpt"
    module_type: "latent-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: True
    num_classes: 1000

datamodule_config: 
    dataset: "imagenet"
    batch_size: 64
    num_workers: 8 

train_config: 
    max_steps: 1000000
    val_check_interval: 2000
    limit_val_batches: 250
    check_val_every_n_epoch: null
    accelerator: "auto" 
    precision: "bf16-mixed"
    enable_progress_bar: False

model_checkpoint_config: 
    dirpath: "checkpoints/latent-diffusion/imagenet/ternary/"
    filename: "latent-diffusion-imagenet-tsvd_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "latent-diffusion-imagenet"
  name: "tsvd-ternary-reg[1.0]-rank[16]"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"