module_config: 
    model_id: "facebook/DiT-XL-2-256"
    module_type: "latent-diffusion" 
    learning_rate: 0.00001
    weight_decay: 0.00
    class_conditional: True
    num_classes: 1000
    use_cfg: True 
    guidance_scale: 4.0
    cfg_null_class: 1000
    cfg_dropout: 0.1

datamodule_config: 
    dataset: "imagenet"
    batch_size: 12 #32
    num_workers: 8 

train_config: 
    max_steps: 200000 
    val_check_interval: 1000
    limit_val_batches: 200
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    enable_progress_bar: True
    log_every_n_steps: 10

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/lsun-bedrooms/ternary/"
    filename: "pixel-diffusion-lsun-bedrooms-ternary_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "latent-dit-imagenet"
  name: "ternary"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"