# Module configuration - model-specific parameters
module_config:
  module: "dit"
  model_name: "dits8"
  pretrained: false
  learning_rate: 0.0004
  checkpoint: null

# Data module configuration - data-specific parameters
datamodule_config:
  dataset: "imagenet"
  batch_size: 2 #128
  num_workers: 8
  image_size: 256

# Training configuration - trainer-specific parameters
train_config:
  max_epochs: 80
  accumulate_grad_batches: 4
  precision: bf16
  accelerator: "gpu"
  devices: "1"
  strategy: "auto"
  enable_progress_bar: true

# Model checkpoint configuration - checkpoint saving parameters
model_checkpoint_config:
  save_dir: "checkpoints/vit/cifar100"
  monitor: "val_loss"
  filename: "{epoch:02d}-{val_loss:.2f}"
  save_top_k: 3
  mode: "min"
  save_last: true

# Logger configuration - logging parameters
logger_config:
  type: "wandb"
  project: "dit"
  save_dir: "/scratch/oeg1n18"
  log_model: false

# Quantization configuration - quantization-specific parameters
quantization_config:
  quant_type: null