module_config: 
    model_id: "google/ddpm-ema-church-256"
    module_type: "pixel-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: False
    num_classes: null

datamodule_config: 
    dataset: "lsun-bedrooms"
    batch_size: 8 #32
    num_workers: 8 

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 300
    enable_progress_bar: False

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/lsun-bedrooms/ternary/"
    filename: "pixel-diffusion-lsun-bedrooms-ternary_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "pixel-diffusion-lsun-bedrooms"
  name: "ternary"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"