module_config: 
    model_id: "google/ddpm-ema-bedroom-256"
    module_type: "pixel-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: False
    num_classes: null

datamodule_config: 
    dataset: "lsun-bedrooms"
    batch_size: 12 #32
    num_workers: 8 

train_config: 
    max_steps: 1000 
    val_check_interval: 1000 
    limit_val_batches: 100
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    enable_progress_bar: True
    log_every_n_steps: 10

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/lsun-bedrooms/ternary/"
    filename: "pixel-diffusion-lsun-bedrooms-ternary_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "pixel-diffusion-lsun-bedrooms"
  name: "ternary"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"