module_config: 
    module_type: "resnet" 
    model_name: "resnet18"
    num_classes: 100
    learning_rate: 0.001 
    image_size: 224

datamodule_config: 
    dataset: "cifar100"
    batch_size: 128
    num_workers: 0 
    image_size: 224

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 50
    enable_progress_bar: true


model_checkpoint_config: 
    dirpath: "checkpoints/resnet/resnet18_cifar100/tsvdlinear"
    filename: tsvdlinear

logger_config:
  type: "wandb"
  project: "resnet18_cifar100"
  name: "resnet18_tsvdlinear"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "tsvdconv2d"
  reg_scale: 4.0
  reg_type: "l2"
  rank: 16