module_config: 
    module_type: "diffusion" 
    learning_rate: 0.0002

datamodule_config: 
    dataset: "imagenet"
    batch_size: 128
    num_workers: 8 
    image_size: 128

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 10
    enable_progress_bar: True
    val_check_interval: 0.1
    limit_val_batches: 1000

model_checkpoint_config: 
    dirpath: "checkpoints/resnet/diffusion/fp"
    filename: unet_fp

logger_config:
  type: "wandb"
  project: "diffusion"
  name: "unet_fp"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: null