module_config: 
    module_type: "diffusion" 
    learning_rate: 0.0002

datamodule_config: 
    dataset: "imagenet"
    batch_size: 512
    num_workers: 8 
    image_size: 128

train_config: 
    accelerator: "auto" 
    strategy: "ddp"
    devices: "2" 
    num_nodes: 1
    precision: "bf16-mixed"
    max_epochs: 50
    enable_progress_bar: True
    val_check_interval: 0.5

model_checkpoint_config: 
    dirpath: "checkpoints/resnet/diffusion/fp"
    filename: unet_fp

logger_config:
  type: "wandb"
  project: "diffusion"
  name: "unet_fp_ddp"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: null