module_config: 
    module_type: "diffusion" 
    checkpoint: "checkpoints/diffusion/fp/unet_fp.ckpt"
    learning_rate: 0.0002
    batch_size: 256

datamodule_config: 
    dataset: "imagenet"
    batch_size: 256
    num_workers: 8 
    image_size: 128

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 100
    enable_progress_bar: True

model_checkpoint_config: 
    dirpath: "checkpoints/diffusion/ternary"
    filename: "t_unet_{epoch:02d}-{val_loss:.2f}"

logger_config:
  type: "wandb"
  project: "diffusion"
  name: "unet_t"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"