module_config: 
    module_type: "pixel-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: True 
    num_classes: 10

datamodule_config: 
    dataset: "cifar10"
    batch_size: 512
    num_workers: 8 

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 300
    enable_progress_bar: True

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/cifar10/ternary/"
    filename: "pixel-diffusion-fp_{epoch:02d}_val_loss_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "pixel-diffusion-cifar10"
  name: "pixel-diffusion-fp"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"