module_config: 
    model_id: "google/ddpm-cifar10-32"
    module_type: "pixel-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: False
    num_classes: null

datamodule_config: 
    dataset: "cifar10"
    batch_size: 12 #32
    num_workers: 8 

train_config: 
    max_steps: 100000
    val_check_interval: 3000
    limit_val_batches: 400
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    enable_progress_bar: False

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/cifar10/ternary/"
    filename: "pixel-diffusion-cifar10-ternary_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "pixel-diffusion-cifar10"
  name: "ternary"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "t"