module_config: 
    module_type: "pixel-diffusion" 
    learning_rate: 0.0001
    weight_decay: 0.01
    model_size: "small"
    class_conditional: True 
    num_classes: 10

datamodule_config: 
    dataset: "cifar10"
    batch_size: 256
    num_workers: 8 

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 150
    enable_progress_bar: True

model_checkpoint_config: 
    dirpath: "checkpoints/pixel-diffusion/cifar10/tsvd-ternary/"
    filename: "pixel-diffusion-tsvd-ternary_rank[8]_reg[0.25]_{epoch:02d}_{val_loss:.3f}"

logger_config:
  type: "wandb"
  project: "pixel-diffusion-cifar10"
  name: "pixel-diffusion-tsvd-ternary"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: "tsvdconv2d"
  reg_scale: 0.25
  reg_type: "l2"
  rank: 8