module_config: 
    model_id: "google/ddpm-cifar10-32"
    module_type: "diffusion" 
    learning_rate: 0.0002
    weight_decay: 0.00
    pixel_space: True
    max_steps: 100000
    warmup_steps: 1000
    use_ema: True 
    ema_decay: 0.999

datamodule_config: 
    dataset: "cifar10"
    batch_size: 128 #32
    num_workers: 8 

train_config: 
    max_steps: 100000
    val_check_interval: 5000
    check_val_every_n_epoch: null
    limit_val_batches: 350
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    enable_progress_bar: True
    gradient_clip_val: 0.5

logger: True 
checkpoint: True 

quantization_config:
  quant_type: "tsvd"
  reg_scale: 0.5
  reg_type: "l2"
  rank: 32