module_config: 
    module_type: "stablediffusion" 
    pretrained: True

datamodule_config: 
    dataset: "imagenet"
    batch_size: 64
    num_workers: 8 
    image_size: 256

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "bf16-mixed"
    max_epochs: 50
    enable_progress_bar: False
    val_check_interval: 0.1
    limit_val_batches: 1000

model_checkpoint_config: 
    dirpath: "checkpoints/resnet/stable_diffusion/tsvd"
    filename: tsvd

logger_config:
  type: "wandb"
  project: "stable-diffusion"
  name: "tsvd_qat"
  save_dir: "logs/"
  log_model: false

quantization_config:
  quant_type: "tsvd"
  reg_scale: 4.0
  reg_type: "l2"
  rank: 16