

module_config: 
    module_type: "resnet" 
    model_name: "resnet50_untrained"
    num_classes: 10
    learning_rate: 0.001 
    image_size: 224


datamodule_config: 
    dataset: "cifar10"
    batch_size: 32
    num_workers: 0 
    image_size: 224

train_config: 
    accelerator: "auto" 
    strategy: "auto"
    precision: "16-mixed"
    max_epochs: 20 
    enable_progress_bar: true
    val_check_interval: 0.1

model_checkpoint_config: 
    dirpath: "checkpoints/resnet/resnet18_cifar10"
    filename: resnet18_cifar10

logger_config:
  type: "wandb"
  project: "resnet18_cifar10"
  save_dir: "logs/"
  log_model: false
 
quantization_config:
  quant_type: null